apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
    spec:
      containers:
      - name: my-k8s-app
        image: my-k8s-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MY_ENV_VAR
          value: "some-value"  # Add any required environment variables here

---

apiVersion: v1
kind: Service
metadata:
  name: my-k8s-app-service
spec:
  selector:
    app: my-k8s-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort  # Can be NodePort, LoadBalancer, or ClusterIP depending on your use case
