apiVersion: v1
kind: Service
metadata:
  name: my-k8s-app-service
spec:
  selector:
    app: my-k8s-app  # Must match the label of the pods in the Deployment
  ports:
    - protocol: TCP
      port: 80         # The port the service exposes
      targetPort: 5000 # The port the container is listening on
  type: NodePort       # Exposes the service on a random port on Minikube
